// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ListComponent$ReactTemplate = require("./ListComponent.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, ListComponent$ReactTemplate.make(/* array */[])), "index");

/*  Not a pure module */
